# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fawkesreq.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fawkesreq.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x66\x61wkesreq.proto\"(\n\tFawkesReq\x12\x0e\n\x06\x61ppkey\x18\x01 \x01(\t\x12\x0b\n\x03\x65nv\x18\x02 \x01(\t'
)




_FAWKESREQ = _descriptor.Descriptor(
  name='FawkesReq',
  full_name='FawkesReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='appkey', full_name='FawkesReq.appkey', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='env', full_name='FawkesReq.env', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=59,
)

DESCRIPTOR.message_types_by_name['FawkesReq'] = _FAWKESREQ
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FawkesReq = _reflection.GeneratedProtocolMessageType('FawkesReq', (_message.Message,), {
  'DESCRIPTOR' : _FAWKESREQ,
  '__module__' : 'fawkesreq_pb2'
  # @@protoc_insertion_point(class_scope:FawkesReq)
  })
_sym_db.RegisterMessage(FawkesReq)


# @@protoc_insertion_point(module_scope)
