# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: locale.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='locale.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0clocale.proto\"\x8f\x01\n\x06Locale\x12\"\n\x07\x63Locale\x18\x01 \x01(\x0b\x32\x11.Locale.LocaleIds\x12\"\n\x07sLocale\x18\x02 \x01(\x0b\x32\x11.Locale.LocaleIds\x1a=\n\tLocaleIds\x12\x10\n\x08language\x18\x01 \x01(\t\x12\x0e\n\x06script\x18\x02 \x01(\t\x12\x0e\n\x06region\x18\x03 \x01(\t'
)




_LOCALE_LOCALEIDS = _descriptor.Descriptor(
  name='LocaleIds',
  full_name='Locale.LocaleIds',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='language', full_name='Locale.LocaleIds.language', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='script', full_name='Locale.LocaleIds.script', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='region', full_name='Locale.LocaleIds.region', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=160,
)

_LOCALE = _descriptor.Descriptor(
  name='Locale',
  full_name='Locale',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cLocale', full_name='Locale.cLocale', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sLocale', full_name='Locale.sLocale', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_LOCALE_LOCALEIDS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=160,
)

_LOCALE_LOCALEIDS.containing_type = _LOCALE
_LOCALE.fields_by_name['cLocale'].message_type = _LOCALE_LOCALEIDS
_LOCALE.fields_by_name['sLocale'].message_type = _LOCALE_LOCALEIDS
DESCRIPTOR.message_types_by_name['Locale'] = _LOCALE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Locale = _reflection.GeneratedProtocolMessageType('Locale', (_message.Message,), {

  'LocaleIds' : _reflection.GeneratedProtocolMessageType('LocaleIds', (_message.Message,), {
    'DESCRIPTOR' : _LOCALE_LOCALEIDS,
    '__module__' : 'locale_pb2'
    # @@protoc_insertion_point(class_scope:Locale.LocaleIds)
    })
  ,
  'DESCRIPTOR' : _LOCALE,
  '__module__' : 'locale_pb2'
  # @@protoc_insertion_point(class_scope:Locale)
  })
_sym_db.RegisterMessage(Locale)
_sym_db.RegisterMessage(Locale.LocaleIds)


# @@protoc_insertion_point(module_scope)
